title = "Juragan Code"
baseurl = "https://www.juragancode.id/"
languageCode = "id-id"
defaultContentLanguage = "id"

MetaDataFormat = "yaml"

# theme to use (located by default in /themes/bimasakti/)
themesDir = "themes"
theme = "bimasakti"

disqusShortname = "juragancode"

[author]
    name = "Mohammad Arief"
    homepage = "https://twitter.com/ardiantapargo"
    bio = "Pengamat Langit"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"

[permalinks]
    artikel = "/:slug/"

[taxonomies]
    tag = "topik"
    category = "kategori"
    series = "seri"